### ISSUE TITLE
Is it possible to view custom pointclouds in the forge viewer?

### ISSUE THREAD

**Issue by shubhamwagh** [petrbroz/forge-point-clouds#1]
HI!
May I know if it is possible to add custom pointcloud file formats like (.ply) abd visualize it in the forge viewer?

Thanks.

**Comment by YouYue123** [comment]
I guess you might need to implement your own .ply reader to create Point cloud class in threejs env

**Comment by petrbroz** [comment]
Correct, the Forge Viewer itself doesn't support point clouds on its own. This sample code shows how you can use the standard three.js point cloud class within the Forge Viewer, so whatever the three.js implementation can do, you can do :)
